### ISSUE TITLE
Is this fake?

### ISSUE THREAD

**Issue by frank-dspeed** [HumanConnection/documentation#6]
I saw you taking money advertising open source social network hmmm I just wonder that here is nothing.

**Comment by frank-dspeed** [comment]
If not msg me for 2000 a month I get your network done

**Comment by ShalokShalom** [comment]
I am also confused, while I am slightly aware about the people behind.

They seem to think a release is just possible, once the code is in beta stage.

And yes: My understanding of the term open source is also another one.

So, in order to sum this up: 

This one seems to be a closed source project, which might plan to go open source some day.

**Comment by frank-dspeed** [comment]
@ShalokShalom as far as i can see here is nothing and in the concepts is nothing like a development plan only buzz words.

**Comment by ShalokShalom** [comment]
Yes, correct.

There is no source code uploaded, as stated.

**Comment by salamynder** [comment]
There definitly is some code. Hope they open source it soon, though...

**Comment by frank-dspeed** [comment]
@ShalokShalom ah no need i only was interrested i know already it is fake

**Comment by ShalokShalom** [comment]
How?

**Comment by frank-dspeed** [comment]
@ShalokShalom i am good connected to near all Software companys that matter they don't asked about anything no where that means there is nothing not even pre beta stage its only a fake to get some money

**Comment by ShalokShalom** [comment]
Well, first of: All companys matter. Secondly: This is pure guess work.

**Comment by frank-dspeed** [comment]
@ShalokShalom i don't know what your talking about this is closed for me your not affilated with the project and i wish you a wonderful day. I am sure that this guys if they can't bring something online in less then a week don't work because they don't even asked anywhere :) this is not guess thats fact…

3 Facts. 
- No Software because no ability to create one else it would exist
- No Try to create software else a track on Popular used tech would exist.
- Yes sure they could possible plan to start working in 3 years but who cares for that?!?!?

**Comment by salamynder** [comment]
@frank-dspeed You might want to have a look on their facebook page, where a prototype is shown in a vid.
Ideas are almost always bigger than abilities... but more crowd, more abilities...

**Comment by frank-dspeed** [comment]
@salamynder lol i saw this stuff and i don't know what gets discussed here this is a closed issue maybe your not a developer but this is a technical community not a discussion forum.

**Comment by salamynder** [comment]
@frank-dspeed 
Please note again: they got a video demonstration, they had people trying out a beta interface, they took in quite some money with crowdfunding, which demonstrated to some people that they got something, they already stated they want to do a rewrite with VueJs.

So, there seems to be some kind of software of condition: php-static, jQuery, socket.io (for chat)... but barely well structured.

Calling it scam therefore seems to me unjustified. However it's deplorable that it's no yet open sourced, so that a community could gather and be consulted.

**Comment by ShalokShalom** [comment]
@frank-dspeed This was a discussion from your side from the very beginning.

**Comment by frank-dspeed** [comment]
@ShalokShalom it was intended as a question to the repo owner sorry for posting that here in the development community its normal to ask questions via a issue but its not normal that 2 people that have nothing to do with the issue are answering and so alerting me every time
